[package]
name = "llama2_rs"
version = "0.1.0"
edition = "2021"
author = "Tian Lin <lintian06@gmail.com>"

[dependencies]
memmap2 = "0.7.1"
rand = "0.8.5"
rayon = { version = "1.7.0" }
clap = { version = "4.3.21", features = ["derive"] }

[features]
default = []
