name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Get Model and Run tests
      run: |
        wget https://huggingface.co/karpathy/tinyllamas/resolve/main/stories15M.bin
        cargo test --verbose
